# задаем базовый образ (вместо 3.8 можно указать другую версию Python)
FROM python:3.10

# устанавливаем google-chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 \
    chromium \
    ca-certificates \
    wget \
    ffmpeg \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY . .
CMD ["python", "main.py"]

# выставляем нужный порт дисплея
ENV DISPLAY=:99