FROM python:3.9

RUN apt-get update && apt-get install -y ffmpeg && apt-get install g++

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN pip install -r requirements.txt

COPY . /usr/src/app

CMD ["python", "main.py"]